"""Add causation_id to fleet_outbox

Revision ID: 4182cecbfaad
Revises: 006_fleet_timestamp_timezone
Create Date: 2026-04-12 11:15:17.503987
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4182cecbfaad"
down_revision: Union[str, None] = "006_fleet_timestamp_timezone"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("fleet_outbox", sa.Column("causation_id", sa.String(length=26), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("fleet_outbox", "causation_id")
    # ### end Alembic commands ###
