"""initial_schema

Revision ID: 08b0b143dd9b
Revises: 
Create Date: 2026-03-24 20:56:13.691666
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '08b0b143dd9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_export_jobs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_filters_json', sa.Text(), nullable=False),
    sa.Column('result_file_key', sa.String(length=500), nullable=True),
    sa.Column('result_file_expires_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_admin_id', sa.String(length=50), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_export_jobs_admin_created', 'trip_export_jobs', ['created_by_admin_id', 'created_at_utc'], unique=False)
    op.create_index('ix_export_jobs_status_created', 'trip_export_jobs', ['status', 'created_at_utc'], unique=False)
    op.create_table('trip_idempotency_records',
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('endpoint_fingerprint', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.Text(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body_json', sa.Text(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key', 'endpoint_fingerprint')
    )
    op.create_index('ix_idempotency_expires', 'trip_idempotency_records', ['expires_at_utc'], unique=False)
    op.create_table('trip_import_jobs',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('import_mode', sa.String(length=10), nullable=False),
    sa.Column('skip_weather_enrichment', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.String(length=50), nullable=False),
    sa.Column('imported_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('enrichment_pending_count', sa.Integer(), nullable=False),
    sa.Column('enrichment_failed_count', sa.Integer(), nullable=False),
    sa.Column('error_summary_json', sa.Text(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_jobs_admin_created', 'trip_import_jobs', ['created_by_admin_id', 'created_at_utc'], unique=False)
    op.create_index('ix_import_jobs_status_created', 'trip_import_jobs', ['status', 'created_at_utc'], unique=False)
    op.create_table('trip_outbox',
    sa.Column('event_id', sa.String(length=26), nullable=False),
    sa.Column('aggregate_type', sa.String(length=10), nullable=False),
    sa.Column('aggregate_id', sa.String(length=26), nullable=False),
    sa.Column('aggregate_version', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=50), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('partition_key', sa.String(length=26), nullable=False),
    sa.Column('publish_status', sa.String(length=15), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_outbox_aggregate', 'trip_outbox', ['aggregate_type', 'aggregate_id', 'created_at_utc'], unique=False)
    op.create_index('ix_outbox_event_name', 'trip_outbox', ['event_name', 'created_at_utc'], unique=False)
    op.create_index('ix_outbox_status_attempt_created', 'trip_outbox', ['publish_status', 'next_attempt_at_utc', 'created_at_utc'], unique=False)
    op.create_table('trip_trips',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('trip_no', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_slip_no', sa.String(length=100), nullable=True),
    sa.Column('source_payload_hash', sa.String(length=64), nullable=True),
    sa.Column('base_trip_id', sa.String(length=26), nullable=True),
    sa.Column('driver_id', sa.String(length=50), nullable=False),
    sa.Column('vehicle_id', sa.String(length=50), nullable=True),
    sa.Column('trailer_id', sa.String(length=50), nullable=True),
    sa.Column('route_id', sa.String(length=50), nullable=True),
    sa.Column('trip_datetime_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trip_timezone', sa.String(length=50), nullable=False),
    sa.Column('tare_weight_kg', sa.Integer(), nullable=False),
    sa.Column('gross_weight_kg', sa.Integer(), nullable=False),
    sa.Column('net_weight_kg', sa.Integer(), nullable=False),
    sa.Column('is_empty_return', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_actor_type', sa.String(length=20), nullable=False),
    sa.Column('created_by_actor_id', sa.String(length=50), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('soft_deleted_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('soft_deleted_by_actor_id', sa.String(length=50), nullable=True),
    sa.CheckConstraint('gross_weight_kg >= 0', name='ck_trips_gross_positive'),
    sa.CheckConstraint('gross_weight_kg >= tare_weight_kg', name='ck_trips_gross_gte_tare'),
    sa.CheckConstraint('net_weight_kg = gross_weight_kg - tare_weight_kg', name='ck_trips_net_eq_diff'),
    sa.CheckConstraint('net_weight_kg >= 0', name='ck_trips_net_positive'),
    sa.CheckConstraint('tare_weight_kg >= 0', name='ck_trips_tare_positive'),
    sa.ForeignKeyConstraint(['base_trip_id'], ['trip_trips.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_no')
    )
    op.create_index('ix_trips_base_trip', 'trip_trips', ['base_trip_id'], unique=False)
    op.create_index('ix_trips_driver_datetime', 'trip_trips', ['driver_id', 'trip_datetime_utc', 'id'], unique=False, postgresql_using='btree')
    op.create_index('ix_trips_route_datetime', 'trip_trips', ['route_id', 'trip_datetime_utc', 'id'], unique=False, postgresql_using='btree')
    op.create_index('ix_trips_status_datetime', 'trip_trips', ['status', 'trip_datetime_utc', 'id'], unique=False, postgresql_using='btree')
    op.create_index('ix_trips_vehicle_datetime', 'trip_trips', ['vehicle_id', 'trip_datetime_utc', 'id'], unique=False, postgresql_using='btree')
    op.create_index('uq_trips_source_slip_no_telegram', 'trip_trips', ['source_slip_no'], unique=True, postgresql_where="source_type = 'TELEGRAM_TRIP_SLIP'")
    op.create_table('trip_import_job_rows',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('job_id', sa.String(length=26), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('row_status', sa.String(length=10), nullable=False),
    sa.Column('created_trip_id', sa.String(length=26), nullable=True),
    sa.Column('driver_code_raw', sa.String(length=50), nullable=True),
    sa.Column('raw_row_json', sa.Text(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_trip_id'], ['trip_trips.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['trip_import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_import_rows_job_number', 'trip_import_job_rows', ['job_id', 'row_number'], unique=False)
    op.create_index('ix_import_rows_job_status', 'trip_import_job_rows', ['job_id', 'row_status'], unique=False)
    op.create_table('trip_trip_enrichment',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('trip_id', sa.String(length=26), nullable=False),
    sa.Column('enrichment_status', sa.String(length=10), nullable=False),
    sa.Column('route_status', sa.String(length=10), nullable=False),
    sa.Column('weather_status', sa.String(length=10), nullable=False),
    sa.Column('data_quality_flag', sa.String(length=10), nullable=False),
    sa.Column('enrichment_attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_enrichment_error_code', sa.String(length=100), nullable=True),
    sa.Column('next_retry_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_token', sa.String(length=50), nullable=True),
    sa.Column('claim_expires_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_by_worker', sa.String(length=50), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id')
    )
    op.create_index('ix_enrichment_claim_exp', 'trip_trip_enrichment', ['claim_expires_at_utc'], unique=False)
    op.create_index('ix_enrichment_route', 'trip_trip_enrichment', ['route_status'], unique=False)
    op.create_index('ix_enrichment_status_retry', 'trip_trip_enrichment', ['enrichment_status', 'next_retry_at_utc'], unique=False)
    op.create_index('ix_enrichment_weather', 'trip_trip_enrichment', ['weather_status'], unique=False)
    op.create_table('trip_trip_evidence',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('trip_id', sa.String(length=26), nullable=False),
    sa.Column('evidence_source', sa.String(length=30), nullable=False),
    sa.Column('evidence_kind', sa.String(length=20), nullable=False),
    sa.Column('source_slip_no', sa.String(length=100), nullable=True),
    sa.Column('telegram_message_id', sa.String(length=50), nullable=True),
    sa.Column('file_key', sa.String(length=500), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('raw_text_ref', sa.String(length=200), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('normalized_truck_plate', sa.String(length=50), nullable=True),
    sa.Column('normalized_trailer_plate', sa.String(length=50), nullable=True),
    sa.Column('origin_name_raw', sa.String(length=200), nullable=True),
    sa.Column('destination_name_raw', sa.String(length=200), nullable=True),
    sa.Column('raw_payload_json', sa.Text(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_row_number', 'trip_trip_evidence', ['row_number'], unique=False)
    op.create_index('ix_evidence_source_slip', 'trip_trip_evidence', ['evidence_source', 'source_slip_no'], unique=False)
    op.create_index('ix_evidence_telegram_msg', 'trip_trip_evidence', ['telegram_message_id'], unique=False)
    op.create_index('ix_evidence_trip_id', 'trip_trip_evidence', ['trip_id'], unique=False)
    op.create_table('trip_trip_timeline',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('trip_id', sa.String(length=26), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=50), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip_trips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeline_event_created', 'trip_trip_timeline', ['event_type', 'created_at_utc'], unique=False)
    op.create_index('ix_timeline_trip_created', 'trip_trip_timeline', ['trip_id', 'created_at_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timeline_trip_created', table_name='trip_trip_timeline')
    op.drop_index('ix_timeline_event_created', table_name='trip_trip_timeline')
    op.drop_table('trip_trip_timeline')
    op.drop_index('ix_evidence_trip_id', table_name='trip_trip_evidence')
    op.drop_index('ix_evidence_telegram_msg', table_name='trip_trip_evidence')
    op.drop_index('ix_evidence_source_slip', table_name='trip_trip_evidence')
    op.drop_index('ix_evidence_row_number', table_name='trip_trip_evidence')
    op.drop_table('trip_trip_evidence')
    op.drop_index('ix_enrichment_weather', table_name='trip_trip_enrichment')
    op.drop_index('ix_enrichment_status_retry', table_name='trip_trip_enrichment')
    op.drop_index('ix_enrichment_route', table_name='trip_trip_enrichment')
    op.drop_index('ix_enrichment_claim_exp', table_name='trip_trip_enrichment')
    op.drop_table('trip_trip_enrichment')
    op.drop_index('ix_import_rows_job_status', table_name='trip_import_job_rows')
    op.drop_index('ix_import_rows_job_number', table_name='trip_import_job_rows')
    op.drop_table('trip_import_job_rows')
    op.drop_index('uq_trips_source_slip_no_telegram', table_name='trip_trips', postgresql_where="source_type = 'TELEGRAM_TRIP_SLIP'")
    op.drop_index('ix_trips_vehicle_datetime', table_name='trip_trips', postgresql_using='btree')
    op.drop_index('ix_trips_status_datetime', table_name='trip_trips', postgresql_using='btree')
    op.drop_index('ix_trips_route_datetime', table_name='trip_trips', postgresql_using='btree')
    op.drop_index('ix_trips_driver_datetime', table_name='trip_trips', postgresql_using='btree')
    op.drop_index('ix_trips_base_trip', table_name='trip_trips')
    op.drop_table('trip_trips')
    op.drop_index('ix_outbox_status_attempt_created', table_name='trip_outbox')
    op.drop_index('ix_outbox_event_name', table_name='trip_outbox')
    op.drop_index('ix_outbox_aggregate', table_name='trip_outbox')
    op.drop_table('trip_outbox')
    op.drop_index('ix_import_jobs_status_created', table_name='trip_import_jobs')
    op.drop_index('ix_import_jobs_admin_created', table_name='trip_import_jobs')
    op.drop_table('trip_import_jobs')
    op.drop_index('ix_idempotency_expires', table_name='trip_idempotency_records')
    op.drop_table('trip_idempotency_records')
    op.drop_index('ix_export_jobs_status_created', table_name='trip_export_jobs')
    op.drop_index('ix_export_jobs_admin_created', table_name='trip_export_jobs')
    op.drop_table('trip_export_jobs')
    # ### end Alembic commands ###
