"""Deep verification of the 5 audit claims."""

import logging
from pathlib import Path
from unittest.mock import Mock
import pytest

from trip_service.service import TripService
from trip_service.database import engine
from trip_service.resiliency import CircuitBreaker
from trip_service.config import settings
from trip_service.models import TripTrip


# 1. Verify ETag bug claim
def test_audit_etag_format():
    """Verify service.py uses the correct ETag format generated by middleware, NOT a hardcoded f-string."""
    service = TripService(session=Mock(), auth=Mock())
    trip = TripTrip(id="test12345", version=3, status="COMPLETED")

    headers = service._response_headers(trip)
    assert headers["ETag"] == '"trip-test12345-v3"'


# 2. Verify pool_recycle bug claim
def test_audit_pool_recycle_exists():
    """Verify database.py engine is initialized with pool_recycle."""
    pool_recycle_value = getattr(engine.pool, "_recycle", None)
    assert pool_recycle_value == settings.db_pool_recycle_seconds


# 3. Verify resiliency logging claim
def test_audit_resiliency_lazy_logging(monkeypatch):
    """Verify CircuitBreaker uses proper parameterized logging (%s), NOT f-strings."""
    breaker = CircuitBreaker("test-service", failure_threshold=1)

    mock_logger = Mock()
    monkeypatch.setattr("trip_service.resiliency.logger", mock_logger)

    breaker._handle_failure()

    assert mock_logger.warning.called
    args, kwargs = mock_logger.warning.call_args
    assert "%s" in args[0]
    assert "%d" in args[0]
    assert args[1:] == ("test-service", 1)


# 4. Verify Dockerfile HEALTHCHECK
def test_audit_dockerfile_healthcheck():
    """Verify the Dockerfile contains the HEALTHCHECK instruction."""
    dockerfile_path = Path(__file__).parent.parent / "Dockerfile"
    content = dockerfile_path.read_text()
    assert "HEALTHCHECK" in content
    assert "--interval=" in content
