"""add causation_id to location_outbox

Revision ID: 8cf4a955f5cf
Revises: e1f2a3b4c5d6
Create Date: 2026-04-12 10:33:45.267203
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8cf4a955f5cf"
down_revision: Union[str, None] = "e1f2a3b4c5d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("location_outbox", sa.Column("causation_id", sa.String(length=26), nullable=True))
    op.add_column("location_outbox", sa.Column("correlation_id", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("location_outbox", "correlation_id")
    op.drop_column("location_outbox", "causation_id")
    # ### end Alembic commands ###
