"""initial_schema

Revision ID: 9f4e4fe14d8c
Revises:
Create Date: 2026-03-24 22:25:42.080185
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f4e4fe14d8c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bulk_refresh_jobs",
        sa.Column("bulk_refresh_job_id", sa.UUID(), nullable=False),
        sa.Column("job_status", sa.String(length=50), nullable=False),
        sa.Column("trigger_type", sa.String(length=50), nullable=False),
        sa.Column("selection_scope_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total_pairs", sa.Integer(), nullable=False),
        sa.Column("processed_pairs", sa.Integer(), nullable=False),
        sa.Column("failed_pairs", sa.Integer(), nullable=False),
        sa.Column("skipped_pairs", sa.Integer(), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("started_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("failed_pairs >= 0", name="chk_bulk_refresh_jobs_failed"),
        sa.CheckConstraint("processed_pairs >= 0", name="chk_bulk_refresh_jobs_processed"),
        sa.CheckConstraint("skipped_pairs >= 0", name="chk_bulk_refresh_jobs_skipped"),
        sa.CheckConstraint("total_pairs >= 0", name="chk_bulk_refresh_jobs_total"),
        sa.PrimaryKeyConstraint("bulk_refresh_job_id"),
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("locked_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_headers_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("response_body", sa.String(), nullable=True),
        sa.Column("response_truncated", sa.Boolean(), nullable=False),
        sa.Column("canonical_request_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key_hash"),
    )
    op.create_table(
        "location_points",
        sa.Column("location_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name_tr", sa.String(length=255), nullable=False),
        sa.Column("name_en", sa.String(length=255), nullable=False),
        sa.Column("normalized_name_tr", sa.String(length=255), nullable=False),
        sa.Column("normalized_name_en", sa.String(length=255), nullable=False),
        sa.Column("latitude_6dp", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("longitude_6dp", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("code ~ '^[A-Z0-9_]{2,32}$'", name="chk_location_points_code_format"),
        sa.CheckConstraint(
            "NOT (latitude_6dp = 0.0 AND longitude_6dp = 0.0)", name="chk_location_points_not_null_island"
        ),
        sa.CheckConstraint("latitude_6dp >= -90.0 AND latitude_6dp <= 90.0", name="chk_location_points_lat"),
        sa.CheckConstraint("longitude_6dp >= -180.0 AND longitude_6dp <= 180.0", name="chk_location_points_lng"),
        sa.PrimaryKeyConstraint("location_id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("latitude_6dp", "longitude_6dp", name="uq_location_points_lat_lng"),
        sa.UniqueConstraint("normalized_name_en"),
        sa.UniqueConstraint("normalized_name_tr"),
    )
    op.create_table(
        "route_export_jobs",
        sa.Column("export_job_id", sa.UUID(), nullable=False),
        sa.Column("job_status", sa.String(length=50), nullable=False),
        sa.Column("scope_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("include_segments", sa.Boolean(), nullable=False),
        sa.Column("file_storage_ref", sa.String(length=512), nullable=True),
        sa.Column("record_count", sa.Integer(), nullable=False),
        sa.Column("expires_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("export_job_id"),
    )
    op.create_table(
        "route_import_jobs",
        sa.Column("import_job_id", sa.UUID(), nullable=False),
        sa.Column("file_storage_ref", sa.String(length=512), nullable=False),
        sa.Column("content_checksum", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=50), nullable=False),
        sa.Column("job_status", sa.String(length=50), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=False),
        sa.Column("processed_rows", sa.Integer(), nullable=False),
        sa.Column("failed_rows", sa.Integer(), nullable=False),
        sa.Column("started_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("import_job_id"),
        sa.UniqueConstraint("content_checksum", "mode", name="uq_route_import_jobs_checksum_mode"),
    )
    op.create_table(
        "route_pairs",
        sa.Column("route_pair_id", sa.UUID(), nullable=False),
        sa.Column("pair_code", sa.String(length=29), nullable=False),
        sa.Column("origin_location_id", sa.UUID(), nullable=False),
        sa.Column("destination_location_id", sa.UUID(), nullable=False),
        sa.Column("profile_code", sa.String(length=32), server_default="TIR", nullable=False),
        sa.Column("pair_status", sa.String(length=50), nullable=False),
        sa.Column("forward_route_id", sa.UUID(), nullable=True),
        sa.Column("reverse_route_id", sa.UUID(), nullable=True),
        sa.Column("current_active_forward_version_no", sa.Integer(), nullable=True),
        sa.Column("current_active_reverse_version_no", sa.Integer(), nullable=True),
        sa.Column("pending_forward_version_no", sa.Integer(), nullable=True),
        sa.Column("pending_reverse_version_no", sa.Integer(), nullable=True),
        sa.Column("row_version", sa.Integer(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("pair_code ~ '^RP_[0-9A-Z]{26}$'", name="chk_route_pairs_pair_code_format"),
        sa.CheckConstraint(
            "(pending_forward_version_no IS NULL AND pending_reverse_version_no IS NULL) OR "
            "(pending_forward_version_no IS NOT NULL AND pending_reverse_version_no IS NOT NULL)",
            name="chk_route_pairs_pending_pointers_atomic",
        ),
        sa.CheckConstraint("origin_location_id != destination_location_id", name="chk_route_pairs_origin_neq_dest"),
        sa.ForeignKeyConstraint(
            ["destination_location_id"],
            ["location_points.location_id"],
        ),
        sa.ForeignKeyConstraint(["forward_route_id"], ["routes.route_id"], use_alter=True),
        sa.ForeignKeyConstraint(
            ["origin_location_id"],
            ["location_points.location_id"],
        ),
        sa.ForeignKeyConstraint(["reverse_route_id"], ["routes.route_id"], use_alter=True),
        sa.PrimaryKeyConstraint("route_pair_id"),
        sa.UniqueConstraint("pair_code"),
    )
    op.create_index(
        "idx_route_pairs_active_unique",
        "route_pairs",
        ["origin_location_id", "destination_location_id", "profile_code"],
        unique=True,
        postgresql_where=sa.text("pair_status = 'ACTIVE'"),
    )
    op.create_table(
        "processing_runs",
        sa.Column("processing_run_id", sa.UUID(), nullable=False),
        sa.Column("route_pair_id", sa.UUID(), nullable=False),
        sa.Column("run_status", sa.String(length=50), nullable=False),
        sa.Column("trigger_type", sa.String(length=50), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("provider_mapbox_status", sa.String(length=20), nullable=False),
        sa.Column("provider_ors_status", sa.String(length=20), nullable=False),
        sa.Column("expected_forward_version_no", sa.Integer(), nullable=True),
        sa.Column("expected_reverse_version_no", sa.Integer(), nullable=True),
        sa.Column("bulk_refresh_job_id", sa.UUID(), nullable=True),
        sa.Column("import_job_id", sa.UUID(), nullable=True),
        sa.Column("started_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "provider_mapbox_status IN ('PENDING', 'OK', 'FAILED')", name="chk_processing_runs_mapbox_status"
        ),
        sa.CheckConstraint(
            "provider_ors_status IN ('PENDING', 'OK', 'FAILED', 'UNAVAILABLE')", name="chk_processing_runs_ors_status"
        ),
        sa.ForeignKeyConstraint(
            ["bulk_refresh_job_id"],
            ["bulk_refresh_jobs.bulk_refresh_job_id"],
        ),
        sa.ForeignKeyConstraint(
            ["import_job_id"],
            ["route_import_jobs.import_job_id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_pair_id"],
            ["route_pairs.route_pair_id"],
        ),
        sa.PrimaryKeyConstraint("processing_run_id"),
    )
    op.create_index(
        "idx_processing_runs_queued_running_unique",
        "processing_runs",
        ["route_pair_id"],
        unique=True,
        postgresql_where=sa.text("run_status IN ('QUEUED', 'RUNNING')"),
    )
    op.create_table(
        "routes",
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("route_pair_id", sa.UUID(), nullable=False),
        sa.Column("route_code", sa.String(length=31), nullable=False),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_pair_id"],
            ["route_pairs.route_pair_id"],
        ),
        sa.PrimaryKeyConstraint("route_id"),
        sa.UniqueConstraint("route_code"),
    )
    op.create_table(
        "bulk_refresh_job_items",
        sa.Column("item_id", sa.UUID(), nullable=False),
        sa.Column("bulk_refresh_job_id", sa.UUID(), nullable=False),
        sa.Column("item_no", sa.Integer(), nullable=False),
        sa.Column("route_pair_id", sa.UUID(), nullable=True),
        sa.Column("item_status", sa.String(length=50), nullable=False),
        sa.Column("processing_run_id", sa.UUID(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["bulk_refresh_job_id"], ["bulk_refresh_jobs.bulk_refresh_job_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["processing_run_id"], ["processing_runs.processing_run_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["route_pair_id"], ["route_pairs.route_pair_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("item_id"),
        sa.UniqueConstraint("bulk_refresh_job_id", "item_no", name="uq_bulk_refresh_job_items_no"),
    )
    op.create_table(
        "route_import_job_rows",
        sa.Column("import_job_id", sa.UUID(), nullable=False),
        sa.Column("row_no", sa.Integer(), nullable=False),
        sa.Column("row_status", sa.String(length=50), nullable=False),
        sa.Column("raw_data_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("route_pair_id", sa.UUID(), nullable=True),
        sa.Column("processing_run_id", sa.UUID(), nullable=True),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["import_job_id"], ["route_import_jobs.import_job_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["processing_run_id"], ["processing_runs.processing_run_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["route_pair_id"], ["route_pairs.route_pair_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("import_job_id", "row_no"),
    )
    op.create_table(
        "route_version_counters",
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("next_version_no", sa.Integer(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.route_id"],
        ),
        sa.PrimaryKeyConstraint("route_id"),
    )
    op.create_table(
        "route_versions",
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("processing_run_id", sa.UUID(), nullable=True),
        sa.Column("processing_status", sa.String(length=50), nullable=False),
        sa.Column("total_distance_m", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("total_duration_s", sa.Integer(), nullable=False),
        sa.Column("total_ascent_m", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("total_descent_m", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("avg_grade_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("max_grade_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("steepest_downhill_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("known_speed_limit_ratio", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("segment_count", sa.Integer(), nullable=False),
        sa.Column("validation_result", sa.String(length=50), nullable=False),
        sa.Column("distance_validation_delta_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("duration_validation_delta_pct", sa.Numeric(precision=6, scale=3), nullable=True),
        sa.Column("endpoint_validation_delta_m", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("field_origin_matrix_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("field_origin_matrix_hash", sa.String(length=64), nullable=False),
        sa.Column("road_type_distribution_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("speed_limit_distribution_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("urban_distribution_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("warnings_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("refresh_reason", sa.String(length=255), nullable=True),
        sa.Column("processing_algorithm_version", sa.String(length=50), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("segment_count >= 1", name="chk_route_versions_segment_count"),
        sa.CheckConstraint("total_distance_m >= 0", name="chk_route_versions_total_distance"),
        sa.CheckConstraint("total_duration_s >= 0", name="chk_route_versions_total_duration"),
        sa.ForeignKeyConstraint(
            ["processing_run_id"],
            ["processing_runs.processing_run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.route_id"],
        ),
        sa.PrimaryKeyConstraint("route_id", "version_no"),
    )
    op.create_index(
        "idx_route_versions_active_unique",
        "route_versions",
        ["route_id"],
        unique=True,
        postgresql_where=sa.text("processing_status = 'ACTIVE'"),
    )
    op.create_table(
        "route_import_job_row_errors",
        sa.Column("import_job_id", sa.UUID(), nullable=False),
        sa.Column("row_no", sa.Integer(), nullable=False),
        sa.Column("error_seq", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=False),
        sa.Column("error_message", sa.String(length=512), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_job_id", "row_no"],
            ["route_import_job_rows.import_job_id", "route_import_job_rows.row_no"],
            name="fk_route_import_job_row_errors_row",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("import_job_id", "row_no", "error_seq"),
    )
    op.create_table(
        "route_segments",
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("segment_no", sa.Integer(), nullable=False),
        sa.Column("start_latitude_6dp", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("start_longitude_6dp", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("end_latitude_6dp", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("end_longitude_6dp", sa.Numeric(precision=9, scale=6), nullable=False),
        sa.Column("distance_m", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("start_elevation_m", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("end_elevation_m", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("grade_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("grade_class", sa.String(length=50), nullable=False),
        sa.Column("road_class", sa.String(length=50), nullable=False),
        sa.Column("urban_class", sa.String(length=50), nullable=False),
        sa.Column("speed_limit_kph", sa.Integer(), nullable=True),
        sa.Column("speed_limit_state", sa.String(length=50), nullable=False),
        sa.Column("speed_band", sa.String(length=50), nullable=False),
        sa.Column("tunnel_flag", sa.Boolean(), nullable=False),
        sa.CheckConstraint("distance_m >= 0", name="chk_route_segments_distance"),
        sa.CheckConstraint("segment_no >= 1", name="chk_route_segments_segment_no"),
        sa.ForeignKeyConstraint(
            ["route_id", "version_no"],
            ["route_versions.route_id", "route_versions.version_no"],
            name="fk_route_segments_version",
        ),
        sa.PrimaryKeyConstraint("route_id", "version_no", "segment_no"),
    )
    op.create_table(
        "route_usage_refs",
        sa.Column("route_id", sa.UUID(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("consumer_service", sa.String(length=100), nullable=False),
        sa.Column("consumer_entity_type", sa.String(length=100), nullable=False),
        sa.Column("consumer_entity_id", sa.String(length=100), nullable=False),
        sa.Column("consumer_reported_used_at_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_at_utc", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_id", "version_no"],
            ["route_versions.route_id", "route_versions.version_no"],
            name="fk_route_usage_refs_version",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "route_id", "version_no", "consumer_service", "consumer_entity_type", "consumer_entity_id"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("route_usage_refs")
    op.drop_table("route_segments")
    op.drop_table("route_import_job_row_errors")
    op.drop_index(
        "idx_route_versions_active_unique",
        table_name="route_versions",
        postgresql_where=sa.text("processing_status = 'ACTIVE'"),
    )
    op.drop_table("route_versions")
    op.drop_table("route_version_counters")
    op.drop_table("route_import_job_rows")
    op.drop_table("bulk_refresh_job_items")
    op.drop_table("routes")
    op.drop_index(
        "idx_processing_runs_queued_running_unique",
        table_name="processing_runs",
        postgresql_where=sa.text("run_status IN ('QUEUED', 'RUNNING')"),
    )
    op.drop_table("processing_runs")
    op.drop_index(
        "idx_route_pairs_active_unique", table_name="route_pairs", postgresql_where=sa.text("pair_status = 'ACTIVE'")
    )
    op.drop_table("route_pairs")
    op.drop_table("route_import_jobs")
    op.drop_table("route_export_jobs")
    op.drop_table("location_points")
    op.drop_table("idempotency_keys")
    op.drop_table("bulk_refresh_jobs")
    # ### end Alembic commands ###
