apiVersion: v1
kind: ConfigMap
metadata:
  name: trip-service-config
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability:4317"
  OTEL_TRACES_SAMPLER: "parentbased_traceidratio"
  CORS_ALLOWED_ORIGINS: '["https://lojinext.com"]'
  CORS_ENABLED: "true"